AppCoder/urls.py
from django.urls import path

# views de AppCoder
from AppCoder import views

urlpatterns = [
    path("", views.inicio, name="Inicio"),
    path("cursos/", views.cursos, name="Cursos"),
    path("entregables/", views.ListarEntregables.as_view(), name="Entregables"),
    path("estudiantes/", views.estudiantes, name="Estudiantes"),
    path("profesores/", views.profesores, name="Profesores"),
    path("plantilla/", views.plantilla),
    path("ver_curso/<id>", views.ver_curso, name="VerCurso"),
    path("crear_curso/", views.crear_curso, name="CrearCurso"),
    path("cursos/buscar/", views.buscar_curso, name="BuscarCurso"),
    path("cursos/resultado_buscar/", views.resultado_busqueda_curso, name="ResultBuscarCurso"),

    path("eliminar_curso/<id>", views.eliminar_curso, name="EliminarCurso"),
    path("editar_curso/<id>", views.editar_curso, name="EditarCurso"),
    path("ver_entregable/<pk>", views.VerEntregable.as_view(), name="VerEntregable"),
    path("editar_entregable/<pk>", views.EditarEntregable.as_view(), name="EditarEntregable"),
    path("crear_entregable/", views.CrearEntregable.as_view(), name="CrearEntregable"),
    path("eliminar_entregable/<pk>", views.EliminarEntregable.as_view(), name="EliminarEntregable"),

    path("login/", views.login_request, name="Login"),
    path("logout/", views.logout_request, name="Logout"),
    path("registrarse/", views.registrarse, name="Registrarse"),
    path("perfil/editar/", views.editar_perfil, name="EditarPerfil"),
]

ProyectoCoder27620/urls.py
from django.contrib import admin
from django.urls import path, include

# Para las urls de static
from django.conf.urls.static import static
from django.conf import settings

from ProyectoCoder27620.views import (
    dia_de_hoy,
    saludo,
    saludo_con_nombre,
    anio_nacimiento,
    con_plantilla,
    probando_template,
    notas,
)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("saludo/", saludo),
    path("saludo/<nombre>", saludo_con_nombre),
    path("hoy/", dia_de_hoy),
    path("anio/<int:edad>", anio_nacimiento),
    path("", con_plantilla),
    path("probando/", probando_template),
    path("notas/", notas),
    # Incluyo urls de AppCoder.
    path("AppCoder/", include("AppCoder.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppCoder/models.py
from django.db import models
from django.contrib.auth.models import User


# Heredamos de models.Model para que la clase sea un "modelo" y se use para crear una
# tabla en la base de datos. Cada vez que se hace un cambio hay que correr
# "python manage.py makemigrations" y "python manage.py migrate" para aplicarlos a la bd.
class Profesor(models.Model):
    # CharField = campo de texto
    nombre = models.CharField(max_length=200)
    apellido = models.CharField(max_length=200)
    profesion = models.CharField(max_length=200)
    # EmailField = campo de email
    email = models.EmailField(max_length=200)
    # Hay más tipos de campos: Integer (números enteros), Date (fecha), etc...

    def __str__(self):
        return f"[Profe] {self.nombre} {self.apellido}"

    # Para que diga 'Profesores' en lugar de 'Profesors' en el admin
    class Meta:
        verbose_name_plural = "profesores"


class Estudiante(models.Model):
    nombre = models.CharField(max_length=200)
    apellido = models.CharField(max_length=200)
    email = models.EmailField()

    # Podemos crearles __str__ como cualquier clase
    def __str__(self):
        return f"{self.nombre} {self.apellido}"


class Curso(models.Model):
    nombre = models.CharField(max_length=200)
    comision = models.IntegerField()

    def __str__(self):
        return f"{self.nombre} {self.comision}"


class Entregable(models.Model):
    nombre = models.CharField(max_length=200)
    fecha = models.DateField()
    entregado = models.BooleanField()

    def __str__(self):
        if self.entregado:
            return f"{self.nombre} ✔"
        else:
            return f"{self.nombre} ✘"


class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="avatares", null=True, blank=True)

AppCoder/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class FormCurso(forms.Form):
    nombre = forms.CharField()
    comision = forms.IntegerField()


class FormRegistrarse(UserCreationForm):
    email = forms.EmailField(
        # Se puede especificar como tiene que ser el widget y los atributos del tag en
        # el html
        widget=forms.EmailInput(
            attrs={"placeholder": "email...", "style": "background-color: antiquewhite"}
        )
    )
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(
        label="Repita la contraseña", widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class FormEditarUsuario(UserCreationForm):
    # Les pongo a todos required=False para que no sean obligatorios
    username = forms.CharField(max_length=255, label="Username", required=False)
    email = forms.EmailField(label="Email", required=False)
    password1 = forms.CharField(
        label="Contraseña", widget=forms.PasswordInput, required=False
    )
    password2 = forms.CharField(
        label="Repita la contraseña", widget=forms.PasswordInput, required=False
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
        help_texts = {k: "" for k in fields}

AppCoder/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from AppCoder.models import Avatar, Curso, Entregable, Estudiante

from .forms import FormCurso, FormEditarUsuario, FormRegistrarse


def inicio(request):
    if request.user.is_authenticated:
        avatar = Avatar.objects.filter(user=request.user.id)[0].imagen.url
        return render(request, "AppCoder/inicio.html", {"avatar": avatar})

    return render(request, "AppCoder/inicio.html")


@login_required
def crear_estudiante(request):
    estudiante = Estudiante(
        nombre="Juancito", apellido="Perez", email="juan.perez@gmail.com"
    )
    # Con .save() guardamos la instancia en la bd.
    estudiante.save()
    return HttpResponse(f"Se creó a {estudiante.nombre} {estudiante.apellido}")


def cursos(request):
    cursos = Curso.objects.all()
    return render(request, "AppCoder/cursos.html", {"cursos": cursos})


def entregables(request):
    return render(request, "AppCoder/entregables.html")


def estudiantes(request):
    return render(request, "AppCoder/estudiantes.html")


def profesores(request):
    return render(request, "AppCoder/profesores.html")


# Les dejo una plantilla genérica con bootstrap
def plantilla(request):
    return render(request, "layout.html")


@login_required
def crear_curso(request):
    if request.method == "POST":
        form = FormCurso(request.POST)

        if form.is_valid():
            info = form.cleaned_data
            nombre = info.get("nombre")
            comision = info.get("comision")
            curso = Curso(nombre=nombre, comision=comision)
            curso.save()
            # Se puede usar redirect() de django.shortcuts que nos permite ir a otra
            # url por su 'name'
            return redirect("Cursos")

    form = FormCurso()
    return render(request, "AppCoder/formCurso.html", {"form": form})


def buscar_curso(request):
    return render(request, "AppCoder/busquedaComision.html")


def resultado_busqueda_curso(request):
    if request.GET.get("comision"):
        comision = request.GET["comision"]
        cursos = Curso.objects.filter(comision__iexact=comision)
        return render(
            request,
            "AppCoder/resultadoBusquedaCursos.html",
            {"cursos": cursos, "comision": comision},
        )

    return redirect("BuscarCurso")


@login_required
def eliminar_curso(request, id):
    # Uso Modelo.objects.get(campo=valor) para obtener una instancia de la BD
    curso = Curso.objects.get(id=id)
    curso.delete()
    # Vuelvo a la lista
    return redirect("Cursos")


@login_required
def editar_curso(request, id):
    curso = Curso.objects.get(id=id)

    if request.method == "POST":
        mi_form = FormCurso(request.POST)
        if mi_form.is_valid():
            info = mi_form.cleaned_data

            curso.nombre = info["nombre"]
            curso.comision = info["comision"]

            curso.save()
            return redirect("Cursos")
        else:
            # Hubo algún error
            ...

    print(curso.nombre)
    mi_form = FormCurso(initial={"nombre": curso.nombre, "comision": curso.comision})
    return render(request, "AppCoder/formCurso.html", {"form": mi_form})


def ver_curso(request, id):
    curso = Curso.objects.get(id=id)
    return render(request, "AppCoder/ver_curso.html", {"curso": curso})


# Uso CBV para entregables
class ListarEntregables(ListView):
    model = Entregable
    template_name = "AppCoder/entregables.html"


class VerEntregable(DetailView):
    model = Entregable
    template_name = "AppCoder/ver_entregable.html"


class EditarEntregable(LoginRequiredMixin, UpdateView):
    model = Entregable
    success_url = "/AppCoder/entregables/"
    fields = ["nombre", "fecha", "entregado"]
    # También le podemos decir un template en específico
    template_name = "AppCoder/formEntregable.html"


class CrearEntregable(LoginRequiredMixin, CreateView):
    model = Entregable
    success_url = "/AppCoder/entregables/"
    fields = ["nombre", "fecha", "entregado"]
    # También le podemos decir un template en específico
    template_name = "AppCoder/formEntregable.html"


class EliminarEntregable(LoginRequiredMixin, DeleteView):
    model = Entregable
    success_url = "/AppCoder/entregables/"


def registrarse(request):
    if request.method == "POST":
        form = FormRegistrarse(data=request.POST)
        if form.is_valid():
            form.save()
            # Uso el 'username' del form para obtener el usuario y loguearlo
            username = form.cleaned_data["username"]
            user = User.objects.get(username=username)
            login(request, user)

            # Vuelvo a inicio
            return redirect("Inicio")
        else:
            error = True

    else:
        error = False
        form = FormRegistrarse()

    return render(request, "AppCoder/registrarse.html", {"form": form, "error": error})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            usuario = form.cleaned_data.get("username")
            contra = form.cleaned_data.get("password")
            user = authenticate(username=usuario, password=contra)
            if user:
                login(request, user)
                return redirect("Inicio")

    # Si no me enviaron datos o me los enviaron mal voy al form
    form = AuthenticationForm()
    return render(request, "AppCoder/login.html", {"form": form})


# Puedo usar la funcion logout() de django.contrib.auth para cerrar sesión
def logout_request(request):
    logout(request)
    return redirect("Inicio")


@login_required
def editar_perfil(request):
    usuario = request.user
    if request.method == "POST":
        # Me guardo la info antes de pasarla al formulario para poder
        # chequear si el nombre de usuario es el mismo al de antes.
        post_data = {
            "username": request.POST.get("username"),
            "email": request.POST.get("email"),
            "password1": request.POST.get("password1"),
            "password2": request.POST.get("password2"),
        }
        # Si es el mismo username lo mando vacio para que no me de error
        # por ya existir un usuario con ese username.
        if post_data.get("username") == usuario.username:
            post_data["username"] = None
        form = FormEditarUsuario(data=post_data)
        if form.is_valid():
            info = form.cleaned_data

            email = info.get("email")
            if email:
                usuario.email = email

            username = info.get("username")
            if username:
                usuario.username = username

            pass1 = info.get("password1")
            pass2 = info.get("password2")
            if pass1 and pass2:
                # uso set_password para setear la nueva contraseña encriptada
                usuario.set_password(pass1)
                # set password cierra sesion así que vuelvo a hacer login
                login(request, usuario)

            usuario.save()
            # Vuelvo a inicio
            return redirect("Inicio")
        else:
            error = True

    else:
        error = False
        form = FormEditarUsuario(
            # El form comienza con los campos propios completos
            # (excepto la contraseña)
            initial={
                "username": usuario.username,
                "email": usuario.email,
            }
        )

    return render(request, "AppCoder/formPerfil.html", {"form": form, "error": error})

AppCoder/templates/AppCoder/busquedaComision.html
{% extends 'AppCoder/layout.html' %}
{% block contenido %}
    <div class="mx-auto col-lg-7 col-md-6">
        <h1 class="text-center">Buscar curso</h1>
        <form class="d-flex"
              action="{% url 'ResultBuscarCurso' %}"     
              method="get"
        >
            <input
              class="form-control me-2"
              type="number"
              placeholder="Buscar..."
              name="comision"
              aria-label="Search"
            />
            <button class="btn btn-outline-success" type="submit">
              Buscar
            </button>
          </form>
    </div>
{% endblock contenido %}

AppCoder/templates/AppCoder/cursos.html
{% extends 'AppCoder/layout.html' %}
{% load static %}

{% block contenido %}
    <h1 class="text-center">
        Cursos
    </h1>
    <div class="my-4 col-md-7 col-lg-6 mx-auto">
        <a href="{% url 'CrearCurso' %}" class="btn btn-primary">Crear curso</a>
        <a href="{% url 'BuscarCurso' %}" class="btn btn-success">Buscar</a>
        <div class="mt-3 card bg-light p-3">
            
            {% if not cursos %}            
                <h5>Aca eventualmente mostraré los cursos</h5>
            {% endif %}
                
            {% for curso in cursos %}
                <div class="d-flex justify-content-between my-2 align-items-center">
                    <h5 class="m-0">
                        <a href="{% url 'VerCurso' curso.id %}">
                          {{ curso }}
                        </a>
                    </h5>
                    <div>
                        <a href="{% url 'EditarCurso' curso.id %}"
                           class="btn btn-warning">
                            Editar
                        </a>
                        <a href="{% url 'EliminarCurso' curso.id %}"
                           class="btn btn-danger">
                            Borrar
                        </a>
                    </div>
                </div>
            {% endfor %}
            
        </div>
    </div>
{% endblock contenido %}

AppCoder/templates/AppCoder/entregable_confirm_delete.html
{% extends 'AppCoder/layout.html' %}


{% block contenido %}
    <div class="col-md-7 col-lg-6 mx-auto text-center">
        <h1>Eliminar entregable</h1>
        <form method="post">
            {% csrf_token %}
            ¿Está seguro de que desea eliminar el entregable {{ entregable }}?
            <input type="submit" value="Aceptar">
        </form>
    </div>
{% endblock contenido %}
    

AppCoder/templates/AppCoder/entregables.html
{% extends 'AppCoder/layout.html' %}
{% load static %}

{% block contenido %}
    <h1 class="text-center">
        Entregables
    </h1>

    <div class="my-4 col-md-7 col-lg-6 mx-auto">
        <a href="{% url 'CrearEntregable' %}" class="btn btn-primary">Crear entregable</a>
        <div class="mt-3 card bg-light p-3">
            
            {% if not entregable_list %}            
                <h5>Aca eventualmente mostraré los entregables</h5>
            {% endif %}
                
            {% for entregable in entregable_list %}
                <div class="d-flex justify-content-between my-2 align-items-center">
                    <h5 class="m-0">
                        <a href="{% url 'VerEntregable' entregable.id %}">
                        {{ entregable }}
                        </a>
                    </h5>
                    <div>
                        <a href="{% url 'EditarEntregable' entregable.id %}"
                        class="btn btn-warning">
                            Editar
                        </a>
                        <a href="{% url 'EliminarEntregable' entregable.id %}"
                        class="btn btn-danger">
                            Borrar
                        </a>
                    </div>
                </div>
            {% endfor %}
            
        </div>
    </div>
{% endblock contenido %}

AppCoder/templates/AppCoder/formCurso.html
{% extends 'AppCoder/layout.html' %}
{% block contenido %}
<div class="mx-auto col-xl-5 col-lg-6 col-md-7">
    <h1 class="text-center">Form curso</h1>
    <form method="post" class="text-center d-flex justify-content-center flex-column mt-3">
        {% csrf_token %}
        
        <table>
            {{ form.as_table }}
        </table>

        {% comment "Con html" %}
            <p> Nombre: <input type="text" name="nombre" class="form-control"></p>
            <p> Comisión: <input type="text" name="number" class="form-control"></p>
        {% endcomment %}

        <input type="submit" value="Enviar" class="btn btn-primary mt-3">
    </form>
</div>
{% endblock contenido %}

AppCoder/templates/AppCoder/formEntregable.html
{% extends 'AppCoder/layout.html' %}
{% load static %}

{% block contenido %}
    <h1 class="text-center">
        Form Entregable
    </h1>

    <!-- Pongo clases de bootstrap para que se vea bien pero no hace falta -->
    <form action="" method="POST"
          class="d-flex justify-content-center flex-column col-md-7 col-lg-6 mx-auto"
    >
        {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="Enviar" class="my-3" required>
    </form>
{% endblock contenido %}

AppCoder/templates/AppCoder/formPerfil.html
{% extends 'AppCoder/layout.html' %}
{% block contenido %}
<div class="mx-auto col-xl-5 col-lg-6 col-md-7">
    <h1 class="text-center">Editar perfil</h1>
    <form method="post" class="text-center d-flex justify-content-center flex-column mt-3">
        {% csrf_token %}
        
        <table>
            {{ form.as_table }}
        </table>

        <input type="submit" value="Enviar" class="btn btn-primary mt-3">
    </form>
</div>
{% endblock contenido %}

AppCoder/templates/AppCoder/inicio.html
{% extends 'AppCoder/layout.html' %}
{% block contenido %}
    <h1 class="text-center">Inicio</h1>

    
    {% if user.is_authenticated %}
        {{ user }} <br/>
        <img alt="avatar" style="width: 5rem;" src="{{ avatar }}" />
    {% endif %}
        
{% endblock contenido %}

AppCoder/templates/AppCoder/login.html
{% extends 'AppCoder/cardLayout.html' %}
{% block titulo %}
  Log In
{% endblock titulo %}

{% block enviar %}Iniciar sesión{% endblock enviar %}

AppCoder/templates/AppCoder/profesores.html
{% extends 'AppCoder/layout.html' %}
{% block contenido %}
    <h1 class="text-center">Profesores</h1>
{% endblock contenido %}

AppCoder/templates/AppCoder/registrarse.html
{% extends 'AppCoder/cardLayout.html' %}
{% block titulo %}
  Registrarse
{% endblock titulo %}

{% block enviar %}Registrarse{% endblock enviar %}

AppCoder/templates/AppCoder/resultadoBusquedaCursos.html
{% extends 'AppCoder/layout.html' %}
{% block contenido %}
    <div class="mx-auto col-lg-7 col-md-6">
        <h1 class="text-center">Cursos</h1>
        <p>Comision buscada: {{ comision }}</p>

        <ul>
            {% for curso in cursos %}
                <li>
                    {{ curso }}
                </li>
            {% empty %}
                <h5>No se encontraron resultados que coincidan con su búsqueda</h5>
            {% endfor %}
        </ul>

    </div>
{% endblock contenido %}

AppCoder/templates/AppCoder/ver_curso.html
{% extends 'AppCoder/layout.html' %}


{% block contenido %}
<div class="col-md-7 col-lg-6 mx-auto text-center">
    <h1>Curso</h1>
    <p> Nombre: {{ curso.nombre }}</p>
    <p> Comisión: {{ curso.comision }}</p>
    <a href="{% url 'Cursos' %}">Volver</a>
</div>
{% endblock contenido %}
    

AppCoder/templates/AppCoder/ver_entregable.html
{% extends 'AppCoder/layout.html' %}


{% block contenido %}
<div class="col-md-7 col-lg-6 mx-auto text-center">
    <h1>Entregable</h1>
    <p> Nombre: {{ entregable.nombre }}</p>
    <p> Fecha: {{ entregable.fecha }}</p>
    <p> Entregado: 
        {% if entregable.entregado %}
            Sí
        {% else %}
            No
        {% endif %}
    </p>
    <a href="{% url 'Entregables' %}">Volver</a>
</div>
{% endblock contenido %}
    